yaksh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from interface.views import *
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',"interface.views.show_home",name="home"),

    url(r'^login/$', 'django.contrib.auth.views.login', name="login"), 
    url(r'^logout/$', "interface.views.logout_page",name="logout_page"), 
    url(r'^register/$', "interface.views.register", name="register_page"),
    url(r'^register/success/$', "interface.views.register_success",name="register_success"),    
    url(r'^dashboard/$',"interface.views.next_login",name="next_login"),

    url(r'^questions/$',"interface.views.show_questions_stu",name="stu_questions"),
    url(r'^questions/ratemcq/$',"interface.views.rate_mcq",name="rate_mcq"),
    url(r'^questions/postcomment/$',"interface.views.rate_post",name="rate_post_comment"),
    url(r'^questions/ratecq/$',"interface.views.rate_cq",name="rate_cq"),
    url(r'^questions/addmcq/$',"interface.views.add_mcquestion",name="add_mcq"),  
    url(r'^questions/addcq/$',"interface.views.add_cquestion",name="add_cq"),  

    url(r'^questions/(?P<id>\d+)/$',"interface.views.add_comment",name="question_comment"),
    url(r'^questions/(?P<id>\d+)/postcomment/$',"interface.views.post_comment",name="question_comment_post"),

    url(r'^moderator/$',"interface.views.next_login",name="mod_show"),
    url(r'^moderator/all/$',"interface.views.show_questions_mod_all",name="mod_show_all"),
    url(r'^moderator/mcq/$',"interface.views.show_questions_mod_mcq",name="mod_show_mcq"),
    url(r'^moderator/cq/$',"interface.views.show_questions_mod_cq",name="mod_show_cq"),
    url(r'^moderator/mcq_approved/$',"interface.views.show_questions_mod_approved_mcq",name="mod_show_approved_mcq"),
    url(r'^moderator/cq_approved/$',"interface.views.show_questions_mod_approved_cq",name="mod_show_approved_cq"),
    url(r'^moderator/(?P<id>\d+)/$',"interface.views.approve_questions",name="mod_questions"),
    url(r'^moderator/(?P<id>\d+)/approve/$',"interface.views.approve_questions_accept",name="mod_approve"),
    url(r'^moderator/(?P<id>\d+)/postcomment/$',"interface.views.post_comment",name="mod_approve_posted"),
                      
    url(r'^reviews/$',"interface.views.show_reviews",name="show_review"),
    url(r'^ratings/$',"interface.views.show_ratings",name="show_ratings"),


  
]

interface/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

language = (
        ("python", "Python"),
        ("bash", "Bash"),
        ("c", "C Language"),
        ("cpp", "C++ Language"),
        ("java", "Java Language"),
        ("scilab", "Scilab"),
    )


question_types = (
        ("mcq", "Multiple Choice"),
        ("mcc", "Multiple Correct Choices"),
        ("code", "Code"),
    )

test_case_types = (
        ("standardtestcase", "Standard Testcase"),
        ("stdoutbasedtestcase", "Stdout Based Testcase"),
        ("mcqtestcase", "MCQ Testcase"),
    )

question_status_choice = (
        (1, "approved"),
        (0, "unseen"),
        (-1, "discarded"),
        )

level = (
		(1, "easy"),
		(2, "medium"),
		(3, "difficult"),
		)

rating_choice = (
        (1, "Poor"),
        (2, "Average"),
        (3, "Good"),
        (4, "Verygood"),
        (5, "Excellent"),
	    )
types = (
		(1, "integer"),
		(2, "float"),
		(3, "string"),
		(4, "boolean"),
		)

class Question(models.Model):
	title = models.CharField(max_length=50, default="")
	text = models.TextField(default="")
	language = models.CharField(max_length=24, choices=language, default='python')
	marks = models.IntegerField(default=0)
	status = models.IntegerField(default=0, choices=question_status_choice)
	user = models.ForeignKey(User,default=0)
	avg_rating=models.IntegerField(default=0)
	
	def __str__(self):
		return  self.text
	
	def approve(self):
		self.status=1
	
	def disapprove(self):
		self.status=0

class MultipleChoiceQuestion(Question):
	no_of_inputs = models.IntegerField(default=4)
	
	def __str__(self):
	    return  self.text
	    
class Choice(models.Model):
    text = models.TextField(default='')
    question = models.ForeignKey(MultipleChoiceQuestion)
    correct = models.BooleanField(default=False)
    
    def __str__(self):
    	return self.text   


class CodeQuestion(Question):
	function_name = models.CharField(max_length=100, default=None)
	
	def __str__(self):
		return str(self.text)

class TestCase(models.Model):
	
	no_of_inputs = models.IntegerField()
	no_of_outputs = models.IntegerField()
	question = models.ForeignKey(CodeQuestion)
	
	
	def __str__(self):
		return str(self.id)
	

class Rating(models.Model):
	user = models.ForeignKey(User)
	question = models.ForeignKey(Question)
	rate = models.IntegerField(default=3, choices=rating_choice)
	
	def __str__(self):	
		return str(self.user)
		
	class Meta:
		unique_together = ('user', 'question',) 

class Review(models.Model):
	reviewer = models.ForeignKey(User)
	question = models.ForeignKey(Question)
	comments = models.CharField(max_length=24, choices=level)
	
	def __str__(self):	
		return str(self.reviewer)
	
	def update_review(self,new_comments):
		self.comments=new_comments
	#class Meta:
	#	unique_together = ('reviewer', 'question',) 



class Input(models.Model):
	_type = models.CharField(max_length=24, choices=types)
	value = models.CharField(max_length=24)
	test_cases = models.ForeignKey('TestCase')
	
	def __str__(self):
		return str(self._type) +"+"+ str(self.value)

class Output(models.Model):
	_type = models.CharField(max_length=24, choices=types)
	value = models.CharField(max_length=24)
	test_cases = models.ForeignKey('TestCase')
	
	def __str__(self):
		return str(self._type) +"+"+ str(self.value)

templates/add_cquestion.html
{% extends "navigation.html" %}
{% block navbar %}
<li class="active"><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'next_login' %}">Contribution</a></li>
<li><a href="{% url 'logout_page' %}">Logout</a></li>
 {% endblock %}
{% block content %}
	<form method="post" onsubmit="return validateForm();">
	
	<h2>Add Code Question</h2>
	<table id="ok">
		{{ form.as_table }}
	<tr><td><b>No of inputs: </b></td><td> <input type="number" id="id_no_of_inputs" name="no_of_inputs"  value="2" /></td></tr>
	<tr><td><b>No of outpus: </b></td><td> <input type="number" id="id_no_of_outputs" name="no_of_outputs"  value="2" /></td></tr>
	<tr><td><b>No of test cases: </b></td><td> <input type="number" id="id_no_of_testcases" name="no_of_testcases"  value="0" /></td></tr>
	<tbody id="testcase_container" ></tbody>
	<tr><td></td><td> <input type="Submit" class="btn btn-primary"value="Submit" /></td></tr>
	</table>
	{% csrf_token %}
	</form>


<script src="https://code.jquery.com/jquery-1.7.min.js" integrity="sha256-/05Jde9AMAT4/o5ZAI23rUf1SxDYTHLrkOco0eyRV84=" crossorigin="anonymous"></script>	
<script type='text/javascript'>
$(document).ready( function() {
$('#id_title').on('focus', addFields);
$('#id_no_of_testcases').on('change', addFields);
$('#id_no_of_inputs').on('change', addFields);
$('#id_no_of_outputs').on('change', addFields);
});
function addFields(){
	var ch = document.getElementById("id_no_of_testcases").value;
	var container = document.getElementById("testcase_container");
	script=""
	for(var i=1;i<=ch;i++){
		script+="<tr><td><b>Test Case "+i+"</b></td><td>\n\n<table style='margin-top:20px;margin-bottom:10px;border:1px;'><tbody id='testcase"+i+"_container' ></tbody></table>\n\n</td></tr>"	
		
	}
	container.innerHTML=script;
	for(var i=1;i<=ch;i++){
		update_testcase('testcase'+i);
	}
	
};
function update_testcase(ts_id){
	var input=document.getElementById("id_no_of_inputs").value;
	var output=document.getElementById("id_no_of_outputs").value;
	var container=document.getElementById(ts_id+"_container");
	max=input;
	if (output>max){
		max=output
	}
	script=""
	for (var i=1;i<=max;i++){
		script+="<tr><td>\n"
		if (i<=input){
			script+="\tType: <select name='"+ts_id+"_input_"+i+"_type'><option value='1'>Integer</option><option value='2'>Float</option><option value='3'>String</option><option value='4'>Boolean</option></select><br />\n";
			script+="\t<input name='"+ts_id+"_input_"+i+"_value' type='text' placeholder='"+ts_id+" input "+i+"'  />\n";
		}
		script+="</td><td>\n"
		if (i<=output){
			script+="\tType: <select name='"+ts_id+"_output_"+i+"_type'><option value='1'>Integer</option><option value='2'>Float</option><option value='3'>String</option><option value='4'>Boolean</option></select><br />\n";
			script+="\t<input name='"+ts_id+"_output_"+i+"_value' type='text' placeholder='"+ts_id+" output "+i+"'/>\n";
		}
		script+="</td></tr>\n"
	}
	container.innerHTML=script;

};
function validateForm(){
			title =  document.getElementById("id_title").value;
			if (title==""){
				alert("Enter question title");
				return false;
			}
			
			function_name = document.getElementById("id_function_name").value;
			if (function_name==""){
				alert("Enter function name");
				return false;
			}
			marks = document.getElementById("id_marks").value;
			if (marks<0){
				alert("Marks should be positive");
				return false;
			}
			no_of_inputs = document.getElementById("id_no_of_testcases").value;
			if (no_of_inputs<0){
				alert("No of testcases should be positive");
				return false;
			}
			count = 0;
			for(var i=1;i<=no_of_inputs;i++){
				input_text=document.getElementById("testcase"+i+"_input").value;
				if (input_text<1){
					alert("Enter valid input for testcase "+i);
					return false;
				}
				output_text=document.getElementById("testcase"+i+"_output").value;
				if (output_text<1){
					alert("Enter valid output for testcase "+i);
					return false;
				}
			}
			
}
</script>


{% endblock %}

templates/add_cquestion_old.html
{% extends "navigation.html" %}
{% block navbar %}
<li class="active"><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'next_login' %}">Contribution</a></li>
<li><a href="{% url 'logout_page' %}">Logout</a></li>
 {% endblock %}
{% block content %}
	<form method="post" onsubmit="return validateForm();">
	
	<h2>Add Code Question</h2>
	<table id="ok">
		{{ form.as_table }}
	<tr><td><b>No of test cases: </b></td><td> <input type="number" id="id_no_of_testcases" name="no_of_testcases"  value="0" /></td></tr>
	<tbody id="testcase_container" ></tbody>
	<tr><td></td><td> <input type="Submit" class="btn btn-primary"value="Submit" /></td></tr>
	</table>
	{% csrf_token %}
	</form>


<script src="https://code.jquery.com/jquery-1.7.min.js" integrity="sha256-/05Jde9AMAT4/o5ZAI23rUf1SxDYTHLrkOco0eyRV84=" crossorigin="anonymous"></script>	
<script type='text/javascript'>
$(document).ready( function() {
$('#id_title').on('focus', addFields);
$('#id_no_of_testcases').on('change', addFields);
});
function addFields(){
	var ch = document.getElementById("id_no_of_testcases").value;
	var container = document.getElementById("testcase_container");
	script=""
	for(var i=1;i<=ch;i++){
		script+="<tr><td><b>Test Case "+i+"</b></td><td>\n\n<table><tr><td>  <input type='number' id='testcase"+i+"_input' onchange=\"update_testcase('testcase"+i+"');\" name='testcase"+i+"_input' value=0 placeholder='Testcase "+i+" input' /></td>\n<td>  <input type='number' id='testcase"+i+"_output' value=0 onchange=\"update_testcase('testcase"+i+"');\" name='testcase"+i+"_output' placeholder='Testcase "+i+" output' /> </td></tr> <tbody id='testcase"+i+"_container' ></tbody></table>\n\n</td></tr>\n"
	}
	container.innerHTML=script;
};
function update_testcase(ts_id){
	var input=document.getElementById(ts_id+"_input").value;
	var output=document.getElementById(ts_id+"_output").value;
	var container=document.getElementById(ts_id+"_container");
	max=input;
	if (output>max){
		max=output
	}
	script=""
	console.log(max);
	for (var i=1;i<=max;i++){
		script+="<tr><td>\n"
		if (i<=input){
			script+="\tType: <select name='"+ts_id+"_input_"+i+"_type'><option value='1'>Integer</option><option value='2'>Float</option><option value='3'>String</option><option value='4'>Boolean</option></select><br />\n";
			script+="\t<input name='"+ts_id+"_input_"+i+"_value' type='text' placeholder='"+ts_id+" input "+i+"'  />\n";
		}
		script+="</td><td>\n"
		if (i<=output){
			script+="\tType: <select name='"+ts_id+"_output_"+i+"_type'><option value='1'>Integer</option><option value='2'>Float</option><option value='3'>String</option><option value='4'>Boolean</option></select><br />\n";
			script+="\t<input name='"+ts_id+"_output_"+i+"_value' type='text' placeholder='"+ts_id+" output "+i+"'/>\n";
		}
		script+="</td></tr>\n"
	}
	container.innerHTML=script;
	//alert(script);
};
function validateForm(){
			title =  document.getElementById("id_title").value;
			if (title==""){
				alert("Enter question title");
				return false;
			}
			
			function_name = document.getElementById("id_function_name").value;
			if (function_name==""){
				alert("Enter function name");
				return false;
			}
			marks = document.getElementById("id_marks").value;
			if (marks<0){
				alert("Marks should be positive");
				return false;
			}
			no_of_inputs = document.getElementById("id_no_of_testcases").value;
			if (no_of_inputs<0){
				alert("No of testcases should be positive");
				return false;
			}
			count = 0;
			for(var i=1;i<=no_of_inputs;i++){
				input_text=document.getElementById("testcase"+i+"_input").value;
				if (input_text<1){
					alert("Enter valid input for testcase "+i);
					return false;
				}
				output_text=document.getElementById("testcase"+i+"_output").value;
				if (output_text<1){
					alert("Enter valid output for testcase "+i);
					return false;
				}
			}
			
}
</script>


{% endblock %}

templates/add_mcquestion.html
{% extends "navigation.html" %}
{% block navbar %}
<li class="active"><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'next_login' %}">Contribution</a></li>
<li><a href="{% url 'logout_page' %}">Logout</a></li>
 {% endblock %}
{% block content %}

	<form method="post" onsubmit="return validateForm();" onpageshow="addFields();">
	<h2>Add Multiple Choice Question</h2>
	<table id="ok">
	{{form.as_table}}
	</table>

	<script
			  src="https://code.jquery.com/jquery-1.7.min.js"
			  integrity="sha256-/05Jde9AMAT4/o5ZAI23rUf1SxDYTHLrkOco0eyRV84="
			  crossorigin="anonymous"></script>	
				<script type='text/javascript'>
				$(document).ready( function() {
					console.log("eef")
    				$('#id_no_of_inputs').on('change', addFields);
    				$('#id_title').on('focus', addFields);
				function addFields(){

				var ch = document.getElementById("id_no_of_inputs").value;

				var container = document.getElementById("choice_container");

				while (container.hasChildNodes()) {
				container.removeChild(container.lastChild);
				}
				for (i=1;i<=ch;i++){

				container.appendChild(document.createTextNode("Choice"+(i)));

				var input = document.createElement("input");
				input.type = "text";
				input.name = "choice" + i;
				input.id ="choice"+i;
				input.required;
				container.appendChild(input);
				var input = document.createElement("input");
				input.type = "checkbox";
				input.value="True";
				input.name = "correct" + i;
				input.id ="correct"+i;
				input.required;
				container.appendChild(input);

				container.appendChild(document.createElement("br"));
				}
				document.getElementById("choice_container").innerHTML=container.innerHTML;
				}

			});

				</script>
	<div id="choice_container" >
		
	</div><br /><br />
		{% csrf_token %}

	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit" class="btn btn-primary" value="Submit" /></td></tr>

	</form>
	<script type="text/javascript">
		function validateForm(){
					title =  document.getElementById("id_title").value;
					if (title==""){
						alert("Enter question title");
						return false;
					}
					text = document.getElementById("id_text").value;
					if (text==""){
						alert("Enter question text");
						return false;
					}
					marks = document.getElementById("id_marks").value;
					if (marks<0){
						alert("Marks should be positive");
						return false;
					}
					no_of_inputs = document.getElementById("id_no_of_inputs").value;
					if (no_of_inputs<0){
						alert("No of inputs should be positive");
						return false;
					}
					count = 0;
					for(var i=1;i<=no_of_inputs;i++){
						choice_text=document.getElementById("choice"+i).value;
						if (choice_text==""){
							alert("Enter choice "+i);
							return false;
						}
						if (document.getElementById("correct"+i).checked)
							count++;
					}
					if (count==0){
						alert("Choose atleast one correct option");
						return false;
					}
					
		}
	</script>

  {% endblock %}

templates/base.html
<!DOCTYPE>
<html>
    <head>
    {% load staticfiles %}
        <title>Django Login Application |
        {% block title %}{% endblock %}</title>
    </head>
    <body>
        <h1>{% block head %}{% endblock %}</h1>
        {% block content %}{% endblock %}
 
    </body>
</html>

templates/display_questions.html
{% extends "navigation.html" %}
{% block navbar %}
<li class="active"><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'next_login' %}">Contribution</a></li>
<li><a href="{% url 'logout_page' %}">Logout</a></li>
 {% endblock %}
{% block content %}
<html>
<head>
	<title> Yaksh</title>
</head>
<body>
	<h2>List of Questions: </h2>


	<ul>
	{% for each in questions %}
		<li>
		<a href="{{each.id }}" >{{ each.text }}</a>	
		
		</li>

	{% endfor %}

	</ul>
</body>
</html>
{% endblock %}

templates/display_questions_mod.html
{% extends "navigation.html" %}
{% block navbar %}
<li class="active"><a href="{% url 'home' %}">Home</a></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Show Questions <span class="caret"></span></a>
<ul class="dropdown-menu">
<li><a href="{% url 'mod_show_mcq' %}" >Unapproved MCQ</a></li>
<li><a href="{% url 'mod_show_cq' %}" >Unapproved CQ</a></li>
<li><a href="{% url 'mod_show_approved_mcq' %}">Approved MCQ</a></li>
<li><a href="{% url 'mod_show_approved_cq' %}">Approved CQ</a></li>
</ul>
</li>
<li><a href="{% url 'logout_page' %}">Logout</a></li>
 {% endblock %}
{% block content %}
<html>
<head>
	<title> Yaksh</title>
</head>
<body>
	<h3>{{ title }}</h3>
	<ul>
	{% for each in questions %}
		<li>
		<a href="../{{each.id }}" >{{ each.text }}</a>	
		
		</li>

	{% endfor %}

	</ul>
</body>
</html>
{% endblock %}

templates/display_rating.html
<!DOCTYPE html>
<html>
<head>
	<title> Yaksh | {{ title }}</title>
</head>
<body>
	<ul>
	{% for each in question_ratings %}
		
		<li>
		{{ each.Question.text }}
		<ul>
		{% for each_rating in each.Ratings %}
			<li> 
			
			{{ each_rating.rate }} by {{ each_rating.user }}
			

			
			</li>
		{% endfor %}
		</ul>
		</li>

	{% endfor %}

	</ul>
</body>
</html>

templates/display_review.html
<!DOCTYPE html>
<html>
<head>
	<title> Yaksh | {{ title }}</title>
</head>
<body>
	<ul>
	{% for each in question_reviews %}
		
		<li>
		{{ each.Question.text }}
		<ul>
		{% for each_review in each.Reviews %}
			<li> 
			
			{{ each_review.comments}} by {{ each_review.reviewer }}
			

			
			</li>
		{% endfor %}
		</ul>
		</li>

	{% endfor %}

	</ul>
</body>
</html>

templates/home.html
{% extends "navigation.html" %}
{% block navbar %}
{% ifequal type 'guest' %}
<li class="active"><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'login' %}">Login</a></li>
<li><a href="{% url 'register_page' %}">Signup</a></li>
{% endifequal %}
{% ifequal type 'user' %}
<li class="active"><a href="{% url 'next_login' %}">Home</a></li>
<li><a href="{% url 'next_login' %}">Contribution</a></li>
<li><a href="{% url 'logout_page' %}">Logout</a></li>
{% endifequal %}
{% ifequal type 'moderator' %}
<li class="active"><a href="{% url 'home' %}">Home</a></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Show Questions <span class="caret"></span></a>
<ul class="dropdown-menu">
<li><a href="{% url 'mod_show_mcq' %}" >Unapproved MCQ</a></li>
<li><a href="{% url 'mod_show_cq' %}" >Unapproved CQ</a></li>
<li><a href="{% url 'mod_show_approved_mcq' %}">Approved MCQ</a></li>
<li><a href="{% url 'mod_show_approved_cq' %}">Approved CQ</a></li>
</ul>
</li>
<li><a href="{% url 'logout_page' %}">Logout</a></li>
{% endifequal %}
{% endblock %}

{% block content %}



<html lang="en">
<head>

</head>

<div class="container">
<center>
  <br><br>
  <h1>Welcome to Chethana Question Contribution</h1><br/>
 
 
  </center>
</div>

</body>
</html>
{% endblock %}

templates/index.html
	<!DOCTYPE html>
<html>
<head>
	<title>Yaksh | Home</title>
</head>
<body>
	<h2>Welcome {{ user }}</h2>
	<ul>
	<li><a href="questions">Student Interface</a></li>
	<li><a href="questions">Moderator Interface</a></li>
	
	
		
	</ul>


</body>
</html>

templates/index3.html
	<!DOCTYPE html>
<html>
<head>
	<title>Yaksh | Home</title>
</head>
<body>
	<h2>Welcome {{ user }}</h2>
	<ul>
	<li><a href="questions">Student Interface</a></li>
	
		
	</ul>


</body>
</html>

templates/navigation.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load staticfiles %}
  <title>Yaksh | Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      
    </div>
    <ul class="nav navbar-nav">
    {% block navbar %}
    {% endblock %}

    </ul>
  </div>
</nav>
<div class="container">

  
  {% block content %}
  {% endblock %}
  
</div>

</body>
</html>

templates/notice.html
{% extends "navigation.html" %}
{% block navbar %}

<li class="active"><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'next_login' %}">Contribution</a></li>
<li><a href="{% url 'logout_page' %}">Logout</a></li>
{% endblock %}
{% block content %}
<html lang="en">
<head>

</head>

<div class="container">
<center>
  <br><br>
  <p>{{ notice|safe }}</p>
 
  </center>
</div>

</body>
</html>
{% endblock %}

templates/student.html
{% extends "navigation.html" %}
{% block navbar %}
<li class="active"><a href="{% url 'home' %}">Home</a></li>
<li><a href="{% url 'next_login' %}">Contribution</a></li>
<li><a href="{% url 'logout_page' %}">Logout</a></li>
 {% endblock %}
{% block content %}

<h3>Title: {{ question.title|safe }}</h3>
<b>Creator : </b> {{ question.user }}<br />
<b>Avg. Rating : </b> {{ question.avg_rating }}<br />
<h3>Question</h3>
<ul>
	{% for each in question_choices %}
		<li>
		{{ each.Question.text }}
		<ul>
		{% for each_choice in each.Choices %}
			<li> 
			
			{% if each_choice.correct %}
			<b><u>
			{% endif %}

			{{ each_choice.text }} 

			</u></b>
			</li>
		{% endfor %}
		</ul>
		</li>

	{% endfor %}

	</ul>

<ul>
	{% for each in question_testcases %}
		<li>
		{{ each.Question.text }}
		<ul>
		
		{% for testcase in each.Testcases %}
		<b>Testcase</b>
		<ul>
		Input:
		{% for input in testcase.input %}
				<li>{{input.value}}</li>
		{% endfor %}
		</ul>

		<ul>
		Output:
		{% for output in testcase.output %}
			<li>{{ output.value }}</li>
		{% endfor %}
		</ul>

		{% endfor %}
		
		
		</ul>
		</li>

	{% endfor %}

	</ul>
<h3>Ratings</h3>
<ul>
	{% if ratings_empty %}
	<li>Not yet rated</li>
	{% else %}
	{% for each in question_ratings %}
		{% for each_rating in each.Ratings %}
			<li> 
			{{ each_rating.get_rate_display }} by {{ each_rating.user }}
			</li>
		{% endfor %}
	{% endfor %}
	{% endif %}
	</ul>
<h3>Reviews</h3>
<ul>
	{% if reviews_empty %}
	<li>Not yet reveiwed</li>
	{% else %}
	{% for each in question_reviews %}
		{% for each_review in each.Reviews %}
			<li> 
			{{ each_review.comments}} by {{ each_review.reviewer }}
			</li>
		{% endfor %}
	{% endfor %}
	{% endif %}
	</ul>
<h3>Your opinion: </h3>
<form action="../postcomment/" method="post"  onsubmit="return validate();">
<input type="hidden" name="id" value="{{ question.id}}" />
<input type="hidden" name="rate_type" value="{{rate_type}}" />
 <table>
{% csrf_token %}
<p>
Comment:
<textarea name="content" id="content" cols=20 rows=4></textarea><br/>
Rating:
<select name="rating" id="rating">
<option selected disabled hidden value=0>Select rating</option>
<option value="1">Poor</option>
<option value="2">Average</option>
<option value="3">Good</option>
<option value="4">Very Good</option>
<option value="5">Excellent</option>
</select>
</p>
<input type="submit" value="Post" class="btn btn-primary"/>
</table>
</form><script type="text/javascript ">
function validate(){
	content=document.getElementById("content").value;
	rating=document.getElementById("rating").value;
	if (content==""){
		alert("Please enter review");
		return false;
	}
	else if (rating==0){
		alert("Please choose rating");
		return false;
	}
	return true;
}
</script>


{% endblock %}